version: '3.3'
services:
  coin:
    image: spiddy/coin:v1.0
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 3s
      timeout: 5s
      retries: 1
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: continue
  statuspage:
    image: spiddy/statuspage
    ports:
      - "9000:9000"
    environment:
      - TARGET_URL=http://coin
