apiVersion: v1
kind: Service
metadata:
  labels:
    app: coin
  name: coin
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 31000
    targetPort: 80
  selector:
    app: coin
  type: NodePort
