apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: statuspage
  name: statuspage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statuspage
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: statuspage
    spec:
      containers:
      - name: statuspage
        image: spiddy/statuspage
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGET_URL
          value: http://coin
        ports:
        - containerPort: 80
          protocol: TCP