apiVersion: v1
kind: Service
metadata:
  labels:
    app: statuspage
  name: statuspage
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30000
    targetPort: 9000
  selector:
    app: statuspage
  type: NodePort
